name: mnist-ndigit-env
channels:
  - conda-forge
  - anaconda
  - defaults
  - defaults
dependencies:
  - python=3.9.12
  - pip
  - pip:
    - pandas==1.4.2
    - numpy==1.22.3
    - opencv-python
    - matplotlib==3.5.1
    - scipy==1.8.0
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - joblib
    - torch==1.11.0
    - torchvision==0.12.0
    - tqdm